name: 'CI'

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  phpunit:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - 'ubuntu-latest'
          - 'windows-latest'
        php-version:
          - '8.0'
          - '8.1'
        composer-dependency:
          - 'lowest'
          - 'highest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install Composer and package dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.composer-dependency }}

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --no-interaction --do-not-cache-result --no-coverage
