name: Unit tests

on: [push, pull_request]

jobs:
  unit-tests:
    name: Unit tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [8.0, 8.1]
        stability: [prefer-lowest, prefer-stable]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Run Unit tests
        run: vendor/bin/phpunit --colors=always --verbose --no-interaction
